### ISSUE TITLE
svn.conf file not found

### ISSUE THREAD

**Issue by MrReasonable** [example42/puppet-svn#2]
When I use

```
    class { 'svn':
        version => '1.7.13-1'
        }
```

SVN installs correctly but then I see the following error:

```
Error: Could not set 'present' on ensure: No such file or directory - /etc/subversion/config.conf at 163:/etc/puppet/modules/svn/manifests/init.pp
Error: Could not set 'present' on ensure: No such file or directory - /etc/subversion/config.conf at 163:/etc/puppet/modules/svn/manifests/init.pp
Wrapped exception:
No such file or directory - /etc/subversion/config.conf
Error: /Stage[main]/Svn/File[svn.conf]/ensure: change from absent to present failed: Could not set 'present' on ensure: No such file or directory - /etc/subversion/config.conf at 163:/etc/puppet/modules/svn/manifests/init.pp
```

Obviously I can specify my own svn config but considering that all I want to do is a simple 'yum svn install', I really shouldn't have to.

**Comment by rosaiahch** [comment]
After installing subversion on rhel 7.6, I am not found "**/etc/httpd/conf.d/subversion.conf**" file and doc root directory "**/var/svn**"
yum install subversion mod_dav_svn -y.
svn --> subversion-1.7.14-14.el7.x86_64

Can some one help me.
