### ISSUE TITLE
Puppet Enterprise classification and $source_dir = ''

### ISSUE THREAD

**Issue by goungy** [example42/puppet-svn#4]
## Expected Behavior 
Using classification in Puppet Enterprise should not use source_dir if not explicitely specified

## Actual Behavior
When using classification with Puppet enterprise for this module, $source_dir has default value equal to '' which impact following code in init.pp:
  if $source_dir { <-- $source_dir = ''
    file { 'svn.dir':
      ensure  => directory,
      path    => $config_dir,
      require => Package[$package],
      source  => $source_dir, <-- this equals to '' which is a wrong value
      recurse => true,
      purge   => $bool_source_dir_purge,
      force   => $bool_source_dir_purge,
      replace => $manage_file_replace,
      audit   => $manage_audit,
      noop    => $bool_noops,
    }
  }
It produces following error in Puppet Enterprise:
Failed to apply catalog: Parameter source failed on File[svn.dir]: Cannot use relative URLs '' at /etc/puppetlabs/code/environments/production/modules/svn/manifests/init.pp:168

## Steps to Reproduce the Problem

  1. In nodes/classification from Puppet enterprise console add class svn in a a group of nodes
  2. Execute puppet on the concerned node

## Specifications

Please add this info:
I am not sure behavior is related to facter -p output, but it might be provided if needed.
Puppet version: 4.9.4
Puppet server: 2017.1
No hieradat here

**Comment by alvagante** [comment]
Thank you. Please pull the additional commit, referenced here, where I merged the two conditions
