### ISSUE TITLE
subversion.conf file not found.

### ISSUE THREAD

**Issue by rosaiahch** [example42/puppet-svn#6]
After installing subversion on rhel 7.6, I am not found "/etc/httpd/conf.d/subversion.conf" file and doc root directory "/var/svn"
yum install subversion mod_dav_svn -y.
svn --> subversion-1.7.14-14.el7.x86_64

Can some one help me.

**Comment by rosaiahch** [comment]
I found answer on below url
url: https://www.vultr.com/docs/how-to-setup-an-apache-subversion-svn-server-on-centos-7

**Comment by alvagante** [comment]
Thanks for the question and the answer :)
